# Generated by Django 3.2.7 on 2021-09-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_data', models.CharField(max_length=200)),
                ('to_data', models.CharField(max_length=200)),
            ],
        ),
    ]
