# Generated by Django 3.2.7 on 2021-10-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_data', models.CharField(max_length=200)),
                ('to_data', models.CharField(max_length=200)),
                ('distance', models.IntegerField()),
                ('cost', models.FloatField()),
                ('busnumber', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('uid', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
