# Generated by Django 3.2.7 on 2021-10-28 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20211026_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='distance',
            new_name='ceats',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='cost',
        ),
        migrations.CreateModel(
            name='Stoppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopping', models.CharField(max_length=200)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.bus')),
            ],
        ),
    ]
