# Generated by Django 3.2.7 on 2021-10-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20211028_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stoppings',
            old_name='bus',
            new_name='b',
        ),
    ]
