# Generated by Django 3.2.7 on 2021-10-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_rename_bus_stoppings_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='cost',
            field=models.IntegerField(default=200),
        ),
    ]
